"""Initial migration: create all tables

Revision ID: bb86b6f8fd55
Revises: 
Create Date: 2026-01-09 16:11:01.270590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb86b6f8fd55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databases',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False, comment='数据库ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='数据库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='数据库描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('graph_node_positions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), autoincrement=True, nullable=False, comment='节点画布位置ID'),
    sa.Column('node_id', sa.String(length=100), nullable=False, comment='节点ID (label-name)'),
    sa.Column('database_name', sa.String(length=255), nullable=False, comment='所属数据库名称'),
    sa.Column('x', sa.Float(), nullable=False, comment='X坐标'),
    sa.Column('y', sa.Float(), nullable=False, comment='Y坐标'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_servers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), autoincrement=True, nullable=False, comment='MCP 服务器ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='MCP服务器名称'),
    sa.Column('url', sa.Text(), nullable=False, comment='MCP服务器URL'),
    sa.Column('transport', sa.String(length=100), nullable=False, comment='传输方式'),
    sa.Column('description', sa.Text(), nullable=True, comment='服务器描述'),
    sa.Column('config', sa.JSON(), nullable=True, comment='额外配置信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sdn_controllers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), autoincrement=True, nullable=False, comment='SDN控制器ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='控制器名称'),
    sa.Column('type', sa.String(length=100), nullable=False, comment='控制器类型'),
    sa.Column('host', sa.String(length=255), nullable=False, comment='控制器主机地址'),
    sa.Column('port', sa.Integer(), nullable=False, comment='控制器端口'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='认证用户名'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='认证密码'),
    sa.Column('api_token', sa.Text(), nullable=True, comment='API令牌'),
    sa.Column('status', sa.String(length=100), nullable=False, comment='控制器状态'),
    sa.Column('config', sa.JSON(), nullable=True, comment='额外配置信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdn_controllers_name'), 'sdn_controllers', ['name'], unique=True)
    op.create_table('topology_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), autoincrement=True, nullable=False, comment='拓扑快照ID'),
    sa.Column('controller_id', sa.Integer(), nullable=False, comment='SDN控制器ID'),
    sa.Column('database_name', sa.String(length=255), nullable=False, comment='Neo4j数据库名称'),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False, comment='快照时间'),
    sa.Column('node_count', sa.Integer(), nullable=True, comment='节点数量'),
    sa.Column('link_count', sa.Integer(), nullable=True, comment='链路数量'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='快照描述'),
    sa.Column('extra_metadata', sa.JSON(), nullable=True, comment='额外元数据'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['controller_id'], ['sdn_controllers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_snapshots_database_name'), 'topology_snapshots', ['database_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topology_snapshots_database_name'), table_name='topology_snapshots')
    op.drop_table('topology_snapshots')
    op.drop_index(op.f('ix_sdn_controllers_name'), table_name='sdn_controllers')
    op.drop_table('sdn_controllers')
    op.drop_table('mcp_servers')
    op.drop_table('graph_node_positions')
    op.drop_table('databases')
    # ### end Alembic commands ###
